# Generated by Django 4.2.2 on 2023-06-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='usr',
        ),
    ]
