# Generated by Django 4.2.2 on 2023-06-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myblog_date_myblog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
