# Generated by Django 4.2.2 on 2023-06-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_myblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
