# Generated by Django 4.2.2 on 2023-06-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_myblog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
