# Generated by Django 4.2.2 on 2023-07-04 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_myblog_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 8, 3)),
        ),
        migrations.AddField(
            model_name='usr',
            name='join_date',
            field=models.DateField(auto_now=True),
        ),
    ]
