# Generated by Django 4.2.2 on 2023-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usr_expiry_date_usr_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='blog_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
