# Generated by Django 4.2.2 on 2023-07-04 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usr_blog_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr',
            name='join_date',
            field=models.DateField(default=datetime.date(2023, 7, 4)),
        ),
    ]
