# Generated by Django 4.2.2 on 2023-07-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_usr_expiry_date_alter_usr_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usr',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
