# Generated by Django 4.2.2 on 2023-07-07 07:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_usr_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='id',
        ),
        migrations.AddField(
            model_name='myblog',
            name='blog_id',
            field=models.CharField(default='', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usr',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2023, 8, 6)),
        ),
        migrations.AlterField(
            model_name='usr',
            name='join_date',
            field=models.DateField(default=datetime.date(2023, 7, 7)),
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(default='', upload_to='Blog_Image')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.myblog')),
            ],
        ),
    ]
